name: build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        emacs_version:
          - '26.1'
          - '26.2'
          - '26.3'
          - snapshot

    steps:
      - name: Setup Prerequisites
        run: |
          sudo apt-get install --no-install-recommends -q -y \
            global \
            pandoc \
            exuberant-ctags \
            ripgrep \
            rtags \
            sbcl

      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 1

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run tests
        run: ln -s $GITHUB_WORKSPACE $HOME/.emacs.d && ./run-tests.sh --debug

      - name: Run Shell Check
        if: always()
        run: shellcheck ./run-tests.sh
