name: build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        emacs_version:
          - '26.1'
          - '26.2'
          - '26.3'
          - snapshot

    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 5

      - uses: actions/cache@v1
        name: Setup ELPA packages cache
        with:
          path: ~/.local/lib/emacs/packages
          key: ${{ runner.os }}-elpa-${{ matrix.emacs_version }}-${{ hashFiles('**/init.el') }}
          restore-keys: |
            ${{ runner.os }}-elpa-${{ matrix.emacs_version }}-

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run tests
        run:  ln -s $GITHUB_WORKSPACE $HOME/.emacs.d && ./run-tests.sh --debug
