name: build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        emacs_version:
          - '26.1'
          - '26.2'
          - '26.3'
          - snapshot

    steps:
      - name: Add LLVM repository
        run: |
          wget -q -O llvm-snapshot.gpg.key https://apt.llvm.org/llvm-snapshot.gpg.key
          sudo apt-key add llvm-snapshot.gpg.key
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main"
          sudo apt-get update --quiet --yes 1>/dev/nul

      - name: Setup Prerequisites
        run: |
          sudo apt-get install snapd
          sudo snap install ripgrep --classic

          sudo apt install --no-install-recommends -q -y \
            global \
            pandoc \
            exuberant-ctags \
            sbcl \
            clang-6.0 \
            llvm-6.0 \
            libclang-6.0-dev \
            cmake \
            pkg-config

          echo "::set-env name=CC::clang-6.0"
          echo "::set-env name=CXX::clang++-6.0"

      - name: Download, build and install RTags
        run:  |
          git clone --recursive git@github.com:Andersbakken/rtags.git
          cd rtags
          mkdir build && cd build
          cmake ..
          make -j2
          sudo make install

      - name: Start the RTags daemon
        run: ./rtags/build/bin/rdm &

      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 1

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run tests
        run: ln -s $GITHUB_WORKSPACE $HOME/.emacs.d && ./run-tests.sh --debug

      - name: Run Shell Check
        if: always()
        run: shellcheck ./run-tests.sh
