name: CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        emacs_version:
          - '26.1'
          - '26.2'
          - '26.3'
          - snapshot

    steps:
    - uses: actions/cache@v1
      name: Setup ELPA pacges cache
      id: elpa-packages-cache
      with:
        path: ~/.local/lib/emacs/packages/${{ matrix.emacs_version }}/elpa
        key: elpa-packages-${{ matrix.emacs_version }}-${{ hashFiles('**/init.el') }}
        restore-keys: |
          elpa-packages-${{ matrix.emacs_version }}-

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}


      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 5

      - name: Run tests
        run:  ln -s $GITHUB_WORKSPACE $HOME/.emacs.d && ./run-tests.sh
