name: build

on:
  push:
    paths-ignore:
      - '**.md'

env:
  RTAGS_VERSION: '2.37'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        emacs_version:
          - '26.1'
          - '26.2'
          - '26.3'
          - snapshot
        include:
          - emacs_version: snapshot
            allow_failure: true

    steps:
      - name: Setup Prerequisites
        run: |
          sudo snap install ripgrep --classic
          DEBIAN_FRONTEND=noninteractive sudo apt install --no-install-recommends -qq -y \
            global \
            pandoc \
            exuberant-ctags \
            sbcl \
            cmake

      - name: Checkout Code
        uses: actions/checkout@v2-beta
        with:
          fetch-depth: 1

      - name: Setup GNU Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run tests
        if: matrix.allow_failure != true
        run: ln -s $GITHUB_WORKSPACE $HOME/.emacs.d && ./run-tests.sh --debug

      - name: Run tests
        if: matrix.allow_failure == true
        run: ln -s $GITHUB_WORKSPACE $HOME/.emacs.d && (./run-tests.sh --debug || true)

      - name: Run Shell Check
        if: always()
        run: shellcheck ./run-tests.sh
